<?php

declare(strict_types=1);

return [
    'ctrl' => [
        'title' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tx_gastgeber_domain_model_host',
        'label' => 'title',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'cruser_id' => 'cruser_id',
        'versioningWS' => true,
        'languageField' => 'sys_language_uid',
        'transOrigPointerField' => 'l10n_parent',
        'transOrigDiffSourceField' => 'l10n_diffsource',
        'delete' => 'deleted',
        'enablecolumns' => [
            'disabled' => 'hidden',
            'starttime' => 'starttime',
            'endtime' => 'endtime',
        ],
        'searchFields' => 'title,teaser,description,street,zip,city,email,phone',
        'iconfile' => 'EXT:gastgeber/Resources/Public/Icons/Extension.svg',
        'sortby' => 'sorting',
        'ignorePageTypeRestriction' => true,
    ],
    'types' => [
        '1' => [
            'showitem' => '
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.general,
                    title, slug, teaser, description, media, categories, featured,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.address,
                    --palette--;;addressPalette, --palette--;;mapPalette,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.contact,
                    --palette--;;contactPalette, website, booking_url, booking_text, opening_times,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.prices,
                    --palette--;;capacityPalette, price_from, price_info, season_info, capacity_note,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.equipment,
                    classification_text, equipment_text,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tab.seo,
                    seo_title, meta_description, og_title, og_description, noindex,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,
                    --palette--;;language,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,
                    hidden, starttime, endtime
            ',
        ],
    ],
    'palettes' => [
        'language' => ['showitem' => 'sys_language_uid, l10n_parent, l10n_diffsource'],
        'addressPalette' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:palette.address', 'showitem' => 'street, address_addition, --linebreak--, zip, city, country'],
        'mapPalette' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:palette.map', 'showitem' => 'show_on_map, geocode_on_save, --linebreak--, latitude, longitude'],
        'contactPalette' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:palette.contact', 'showitem' => 'contact_name, phone, --linebreak--, email'],
        'capacityPalette' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:palette.capacity', 'showitem' => 'persons, bedrooms, beds, bathrooms, --linebreak--, size_sqm, units'],
    ],
    'columns' => [
        'sys_language_uid' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.language',
            'config' => ['type' => 'language'],
        ],
        'l10n_parent' => [
            'displayCond' => 'FIELD:sys_language_uid:>:0',
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.l18n_parent',
            'config' => ['type' => 'group', 'allowed' => 'tx_gastgeber_domain_model_host', 'size' => 1, 'maxitems' => 1, 'minitems' => 0, 'default' => 0],
        ],
        'l10n_diffsource' => ['config' => ['type' => 'passthrough']],
        'hidden' => ['exclude' => true, 'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.visible', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle', 'items' => [['label' => '', 'invertStateDisplay' => true]]]],
        'starttime' => ['exclude' => true, 'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.starttime', 'config' => ['type' => 'datetime', 'default' => 0]],
        'endtime' => ['exclude' => true, 'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.endtime', 'config' => ['type' => 'datetime', 'default' => 0]],
        'title' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.title', 'config' => ['type' => 'input', 'required' => true, 'eval' => 'trim', 'max' => 255]],
        'slug' => [
            'label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.slug',
            'config' => [
                'type' => 'slug',
                'generatorOptions' => ['fields' => ['title'], 'fieldSeparator' => '-'],
                'fallbackCharacter' => '-',
                'eval' => 'uniqueInSite',
                'default' => '',
            ],
        ],
        'teaser' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.teaser', 'config' => ['type' => 'text', 'enableRichtext' => true, 'rows' => 4]],
        'description' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.description', 'config' => ['type' => 'text', 'enableRichtext' => true, 'richtextConfiguration' => 'default', 'rows' => 10]],
        'media' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.media', 'config' => ['type' => 'file', 'allowed' => 'common-image-types', 'maxitems' => 99, 'appearance' => ['createNewRelationLinkTitle' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.media.add']]],
        'categories' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.categories', 'config' => ['type' => 'category', 'treeConfig' => ['startingPoints' => ''], 'relationship' => 'manyToMany']],
        'featured' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.featured', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
        'street' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.street', 'config' => ['type' => 'input', 'eval' => 'trim', 'placeholder' => 'Zur Dorfeiche 10']],
        'address_addition' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.address_addition', 'config' => ['type' => 'input', 'eval' => 'trim', 'placeholder' => 'Ortsteil, Hausname, Lagehinweis']],
        'zip' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.zip', 'config' => ['type' => 'input', 'eval' => 'trim', 'default' => '21274']],
        'city' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.city', 'config' => ['type' => 'input', 'eval' => 'trim', 'default' => 'Undeloh']],
        'country' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.country', 'config' => ['type' => 'input', 'eval' => 'trim', 'default' => 'Deutschland']],
        'show_on_map' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.show_on_map', 'description' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.show_on_map.description', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
        'geocode_on_save' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.geocode_on_save', 'description' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.geocode_on_save.description', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle', 'default' => 1]],
        'latitude' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.latitude', 'config' => ['type' => 'input', 'eval' => 'trim,double', 'placeholder' => '53.1966000']],
        'longitude' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.longitude', 'config' => ['type' => 'input', 'eval' => 'trim,double', 'placeholder' => '9.9762000']],
        'contact_name' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.contact_name', 'config' => ['type' => 'input', 'eval' => 'trim']],
        'phone' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.phone', 'config' => ['type' => 'input', 'eval' => 'trim']],
        'email' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.email', 'config' => ['type' => 'email']],
        'website' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.website', 'config' => ['type' => 'link', 'allowedTypes' => ['url', 'page']]],
        'booking_url' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.booking_url', 'config' => ['type' => 'link', 'allowedTypes' => ['url', 'page', 'email']]],
        'booking_text' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.booking_text', 'config' => ['type' => 'text', 'enableRichtext' => true, 'rows' => 5]],
        'opening_times' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.opening_times', 'config' => ['type' => 'text', 'rows' => 4]],
        'price_from' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.price_from', 'config' => ['type' => 'number', 'format' => 'decimal', 'default' => 0]],
        'price_info' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.price_info', 'config' => ['type' => 'text', 'enableRichtext' => true, 'rows' => 5]],
        'persons' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.persons', 'config' => ['type' => 'number', 'default' => 0]],
        'bedrooms' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.bedrooms', 'config' => ['type' => 'number', 'default' => 0]],
        'beds' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.beds', 'config' => ['type' => 'number', 'default' => 0]],
        'bathrooms' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.bathrooms', 'config' => ['type' => 'number', 'default' => 0]],
        'size_sqm' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.size_sqm', 'config' => ['type' => 'number', 'default' => 0]],
        'units' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.units', 'config' => ['type' => 'number', 'default' => 0]],
        'season_info' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.season_info', 'config' => ['type' => 'text', 'rows' => 3]],
        'capacity_note' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.capacity_note', 'config' => ['type' => 'text', 'rows' => 3]],
        'classification_text' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.classification_text', 'config' => ['type' => 'input', 'eval' => 'trim']],
        'equipment_text' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.equipment_text', 'config' => ['type' => 'text', 'enableRichtext' => true, 'rows' => 6]],
        'seo_title' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.seo_title', 'config' => ['type' => 'input', 'eval' => 'trim', 'max' => 255]],
        'meta_description' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.meta_description', 'config' => ['type' => 'text', 'rows' => 3]],
        'og_title' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.og_title', 'config' => ['type' => 'input', 'eval' => 'trim', 'max' => 255]],
        'og_description' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.og_description', 'config' => ['type' => 'text', 'rows' => 3]],
        'noindex' => ['label' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:host.noindex', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
    ],
];
