<?php

declare(strict_types=1);

return [
    'ctrl' => [
        'title' => 'LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tx_gastgeber_domain_model_host',
        'label' => 'title',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'cruser_id' => 'cruser_id',
        'delete' => 'deleted',
        'sortby' => 'sorting',
        'versioningWS' => true,
        'languageField' => 'sys_language_uid',
        'transOrigPointerField' => 'l10n_parent',
        'transOrigDiffSourceField' => 'l10n_diffsource',
        'enablecolumns' => [
            'disabled' => 'hidden',
            'starttime' => 'starttime',
            'endtime' => 'endtime',
        ],
        'searchFields' => 'title,teaser,description,street,zip,city,email,phone,website,external_id',
        'iconfile' => 'EXT:gastgeber/Resources/Public/Icons/Extension.svg',
        'security' => [
            'ignorePageTypeRestriction' => true,
        ],
    ],
    'types' => [
        '1' => [
            'showitem' => '
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,
                    --palette--;;visibility,
                    title, slug, type, district, teaser, description, featured, priority, external_id,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.media,
                    media, logo, documents, video_url,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.addressMap,
                    street, address_addition, zip, city, country, show_on_map, geocode_on_save, latitude, longitude,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.contactBooking,
                    contact_name, phone, mobile, email, website, booking_url, booking_text, request_email,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.pricesCapacity,
                    price_from, price_info, persons, bedrooms, beds, bathrooms, size_sqm, units, season_info, capacity_note,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.features,
                    features, certificates, equipment_text, opening_times, accessibility_text, sustainability_text,
                --div--;LLL:EXT:gastgeber/Resources/Private/Language/locallang_db.xlf:tabs.seo,
                    seo_title, meta_description, og_title, og_description, noindex,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,
                    --palette--;;language,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,
                    --palette--;;access,
                --div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended
            ',
        ],
    ],
    'palettes' => [
        'visibility' => ['showitem' => 'hidden, --linebreak--, starttime, endtime'],
        'language' => ['showitem' => 'sys_language_uid, l10n_parent, l10n_diffsource'],
        'access' => ['showitem' => 'hidden, starttime, endtime'],
    ],
    'columns' => [
        'sys_language_uid' => ['config' => ['type' => 'language']],
        'l10n_parent' => [
            'displayCond' => 'FIELD:sys_language_uid:>:0',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'foreign_table' => 'tx_gastgeber_domain_model_host',
                'foreign_table_where' => 'AND {#tx_gastgeber_domain_model_host}.{#pid}=###CURRENT_PID### AND {#tx_gastgeber_domain_model_host}.{#sys_language_uid} IN (-1,0)',
                'default' => 0,
            ],
        ],
        'l10n_diffsource' => ['config' => ['type' => 'passthrough']],
        'hidden' => ['config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
        'starttime' => ['config' => ['type' => 'datetime', 'default' => 0]],
        'endtime' => ['config' => ['type' => 'datetime', 'default' => 0, 'range' => ['upper' => mktime(0, 0, 0, 1, 1, 2038)]]],
        'title' => ['config' => ['type' => 'input', 'required' => true, 'max' => 255, 'eval' => 'trim']],
        'slug' => [
            'config' => [
                'type' => 'slug',
                'size' => 50,
                'generatorOptions' => [
                    'fields' => ['title'],
                    'fieldSeparator' => '-',
                    'replacements' => ['/'=>'-'],
                ],
                'fallbackCharacter' => '-',
                'eval' => 'uniqueInSite',
                'default' => '',
            ],
        ],
        'type' => [
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'foreign_table' => 'tx_gastgeber_domain_model_type',
                'foreign_table_where' => 'AND {#tx_gastgeber_domain_model_type}.{#hidden}=0 ORDER BY {#tx_gastgeber_domain_model_type}.{#sorting}',
                'minitems' => 0,
                'maxitems' => 1,
                'default' => 0,
            ],
        ],
        'district' => [
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'foreign_table' => 'tx_gastgeber_domain_model_district',
                'foreign_table_where' => 'AND {#tx_gastgeber_domain_model_district}.{#hidden}=0 ORDER BY {#tx_gastgeber_domain_model_district}.{#sorting},{#tx_gastgeber_domain_model_district}.{#title}',
                'items' => [['label' => '', 'value' => 0]],
                'default' => 0,
            ],
        ],
        'teaser' => [
            'label' => 'Teaser / Kurzbeschreibung',
            'description' => 'Kurzer redaktioneller Text für Listen, Teaser-Elemente, Karten und automatische SEO-Beschreibungen. Darf Links und einfache Formatierungen enthalten.',
            'config' => [
                'type' => 'text',
                'enableRichtext' => true,
                'richtextConfiguration' => 'default',
                'rows' => 6,
                'cols' => 80,
                'softref' => 'typolink_tag,email[subst],url',
            ],
        ],
        'description' => [
            'label' => 'Beschreibung',
            'description' => 'Ausführlicher Beschreibungstext für die Detailseite.',
            'config' => [
                'type' => 'text',
                'enableRichtext' => true,
                'richtextConfiguration' => 'default',
                'rows' => 10,
                'cols' => 80,
                'softref' => 'typolink_tag,email[subst],url',
            ],
        ],
        'featured' => ['config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
        'priority' => ['config' => ['type' => 'number', 'size' => 8, 'default' => 0]],
        'external_id' => ['config' => ['type' => 'input', 'max' => 120, 'eval' => 'trim']],
        'media' => ['label' => 'Bildergalerie / Hero-Bild', 'description' => 'Das erste Bild wird als großes Hero-Bild verwendet. Weitere Bilder erscheinen in der Galerie und im Modal.', 'config' => ['type' => 'file', 'allowed' => 'common-image-types', 'maxitems' => 99]],
        'logo' => ['config' => ['type' => 'file', 'allowed' => 'common-image-types', 'maxitems' => 1]],
        'documents' => ['config' => ['type' => 'file', 'allowed' => 'pdf', 'maxitems' => 10]],
        'video_url' => ['config' => ['type' => 'input', 'renderType' => 'inputLink', 'eval' => 'trim']],
        'street' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim']],
        'address_addition' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim']],
        'zip' => ['config' => ['type' => 'input', 'max' => 20, 'eval' => 'trim', 'default' => '21274']],
        'city' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim', 'default' => 'Undeloh']],
        'country' => ['config' => ['type' => 'input', 'max' => 120, 'eval' => 'trim', 'default' => 'Deutschland']],
        'show_on_map' => ['config' => ['type' => 'check', 'renderType' => 'checkboxToggle', 'default' => 1]],
        'geocode_on_save' => ['label' => 'Koordinaten aus Anschrift ermitteln', 'description' => 'Beim Speichern werden Breitengrad und Längengrad aus Straße, PLZ, Ort und Land ermittelt.', 'config' => ['type' => 'check', 'renderType' => 'checkboxToggle', 'default' => 0]],
        'latitude' => ['config' => ['type' => 'input', 'size' => 20, 'eval' => 'trim,double', 'default' => '']],
        'longitude' => ['config' => ['type' => 'input', 'size' => 20, 'eval' => 'trim,double', 'default' => '']],
        'contact_name' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim']],
        'phone' => ['config' => ['type' => 'input', 'max' => 120, 'eval' => 'trim']],
        'mobile' => ['config' => ['type' => 'input', 'max' => 120, 'eval' => 'trim']],
        'email' => ['config' => ['type' => 'email', 'max' => 255]],
        'website' => ['config' => ['type' => 'link', 'allowedTypes' => ['url']]],
        'booking_url' => ['config' => ['type' => 'link', 'allowedTypes' => ['url', 'page']]],
        'booking_text' => ['label' => 'Text in der Box Anfragen / Buchen', 'description' => 'Eigenständiger redaktioneller Text für die Kontakt-/Buchungsbox, unabhängig von Preise & Kapazität.', 'config' => ['type' => 'text', 'enableRichtext' => true, 'richtextConfiguration' => 'default', 'rows' => 5]],
        'request_email' => ['config' => ['type' => 'email', 'max' => 255]],
        'price_from' => ['config' => ['type' => 'number', 'format' => 'decimal', 'default' => 0]],
        'price_info' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'persons' => ['config' => ['type' => 'number', 'default' => 0]],
        'bedrooms' => ['config' => ['type' => 'number', 'default' => 0]],
        'beds' => ['config' => ['type' => 'number', 'default' => 0]],
        'bathrooms' => ['config' => ['type' => 'number', 'default' => 0]],
        'size_sqm' => ['config' => ['type' => 'number', 'default' => 0]],
        'units' => ['config' => ['type' => 'number', 'default' => 0]],
        'season_info' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'capacity_note' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'features' => [
            'label' => 'Merkmale / Ausstattung',
            'description' => 'Strukturierte Merkmale auswählen. Links in der Auswahl steht ein Icon-Hinweis mit Merkmaltext und Gruppe. Im Frontend werden die ersten 6 Merkmale als 3er-Raster angezeigt, weitere Merkmale erscheinen im Modal.',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'foreign_table' => 'tx_gastgeber_domain_model_feature',
                'foreign_table_where' => 'AND {#tx_gastgeber_domain_model_feature}.{#hidden}=0 ORDER BY {#tx_gastgeber_domain_model_feature}.{#group},{#tx_gastgeber_domain_model_feature}.{#sorting},{#tx_gastgeber_domain_model_feature}.{#title}',
                'MM' => 'tx_gastgeber_host_feature_mm',
                'itemsProcFunc' => \D3Werk\Gastgeber\FormEngine\ItemsProcFunc\FeatureItems::class . '->addIconLabels',
                'size' => 18,
                'autoSizeMax' => 30,
                'fieldControl' => [
                    'editPopup' => [
                        'disabled' => false,
                    ],
                    'addRecord' => [
                        'disabled' => false,
                    ],
                    'listModule' => [
                        'disabled' => false,
                    ],
                ],
            ],
        ],
        'certificates' => [
            'label' => 'Klassifizierung / Sterne / Zertifikate',
            'description' => 'Sterne oder Zertifikate wählen. Die erste Stern-Klassifizierung wird als Badge im Bild angezeigt.',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'foreign_table' => 'tx_gastgeber_domain_model_certificate',
                'foreign_table_where' => 'AND {#tx_gastgeber_domain_model_certificate}.{#hidden}=0 ORDER BY {#tx_gastgeber_domain_model_certificate}.{#sorting},{#tx_gastgeber_domain_model_certificate}.{#title}',
                'MM' => 'tx_gastgeber_host_certificate_mm',
                'size' => 8,
                'autoSizeMax' => 20,
            ],
        ],
        'equipment_text' => ['config' => ['type' => 'text', 'enableRichtext' => true, 'richtextConfiguration' => 'default', 'rows' => 8]],
        'opening_times' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'accessibility_text' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'sustainability_text' => ['config' => ['type' => 'text', 'rows' => 4, 'eval' => 'trim']],
        'seo_title' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim']],
        'meta_description' => ['config' => ['type' => 'text', 'rows' => 3, 'eval' => 'trim']],
        'og_title' => ['config' => ['type' => 'input', 'max' => 255, 'eval' => 'trim']],
        'og_description' => ['config' => ['type' => 'text', 'rows' => 3, 'eval' => 'trim']],
        'noindex' => ['config' => ['type' => 'check', 'renderType' => 'checkboxToggle']],
    ],
];
