CREATE TABLE tx_gastgeber_domain_model_host (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    starttime int(11) unsigned DEFAULT '0' NOT NULL,
    endtime int(11) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    t3ver_oid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_wsid int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_state smallint(6) DEFAULT '0' NOT NULL,
    t3ver_stage int(11) DEFAULT '0' NOT NULL,
    t3ver_count int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    t3ver_move_id int(11) unsigned DEFAULT '0' NOT NULL,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    teaser text,
    description mediumtext,
    media int(11) unsigned DEFAULT '0' NOT NULL,
    categories int(11) unsigned DEFAULT '0' NOT NULL,
    street varchar(255) DEFAULT '' NOT NULL,
    address_addition varchar(255) DEFAULT '' NOT NULL,
    zip varchar(20) DEFAULT '' NOT NULL,
    city varchar(255) DEFAULT '' NOT NULL,
    country varchar(120) DEFAULT '' NOT NULL,
    latitude varchar(64) DEFAULT '' NOT NULL,
    longitude varchar(64) DEFAULT '' NOT NULL,
    show_on_map smallint(5) unsigned DEFAULT '0' NOT NULL,
    geocode_on_save smallint(5) unsigned DEFAULT '0' NOT NULL,
    contact_name varchar(255) DEFAULT '' NOT NULL,
    phone varchar(120) DEFAULT '' NOT NULL,
    email varchar(255) DEFAULT '' NOT NULL,
    website varchar(2048) DEFAULT '' NOT NULL,
    booking_url varchar(2048) DEFAULT '' NOT NULL,
    booking_text text,
    price_from decimal(10,2) DEFAULT '0.00' NOT NULL,
    price_info text,
    persons int(11) DEFAULT '0' NOT NULL,
    bedrooms int(11) DEFAULT '0' NOT NULL,
    beds int(11) DEFAULT '0' NOT NULL,
    bathrooms int(11) DEFAULT '0' NOT NULL,
    size_sqm int(11) DEFAULT '0' NOT NULL,
    units int(11) DEFAULT '0' NOT NULL,
    season_info text,
    capacity_note text,
    equipment_text mediumtext,
    opening_times text,
    classification_text varchar(255) DEFAULT '' NOT NULL,
    seo_title varchar(255) DEFAULT '' NOT NULL,
    meta_description text,
    og_title varchar(255) DEFAULT '' NOT NULL,
    og_description text,
    noindex smallint(5) unsigned DEFAULT '0' NOT NULL,
    featured smallint(5) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY language (l10n_parent,sys_language_uid),
    KEY slug (slug(191))
);

CREATE TABLE sys_category (
    tx_gastgeber_icon int(11) unsigned DEFAULT '0' NOT NULL,
    tx_gastgeber_icon_class varchar(255) DEFAULT '' NOT NULL,
    tx_gastgeber_hide_filter smallint(5) unsigned DEFAULT '0' NOT NULL,
    tx_gastgeber_top_feature smallint(5) unsigned DEFAULT '0' NOT NULL,
    tx_gastgeber_is_filter_group smallint(5) unsigned DEFAULT '0' NOT NULL
);
