CREATE TABLE tx_gastgeber_domain_model_host (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    starttime int(11) unsigned DEFAULT '0' NOT NULL,
    endtime int(11) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    type int(11) unsigned DEFAULT '0' NOT NULL,
    district int(11) unsigned DEFAULT '0' NOT NULL,
    teaser text,
    description mediumtext,
    featured smallint(5) unsigned DEFAULT '0' NOT NULL,
    priority int(11) DEFAULT '0' NOT NULL,
    external_id varchar(120) DEFAULT '' NOT NULL,
    media int(11) unsigned DEFAULT '0' NOT NULL,
    logo int(11) unsigned DEFAULT '0' NOT NULL,
    documents int(11) unsigned DEFAULT '0' NOT NULL,
    video_url varchar(2048) DEFAULT '' NOT NULL,
    street varchar(255) DEFAULT '' NOT NULL,
    address_addition varchar(255) DEFAULT '' NOT NULL,
    zip varchar(20) DEFAULT '' NOT NULL,
    city varchar(255) DEFAULT '' NOT NULL,
    country varchar(120) DEFAULT '' NOT NULL,
    latitude varchar(64) DEFAULT '' NOT NULL,
    longitude varchar(64) DEFAULT '' NOT NULL,
    show_on_map smallint(5) unsigned DEFAULT '1' NOT NULL,
    geocode_on_save smallint(5) unsigned DEFAULT '0' NOT NULL,
    contact_name varchar(255) DEFAULT '' NOT NULL,
    phone varchar(120) DEFAULT '' NOT NULL,
    mobile varchar(120) DEFAULT '' NOT NULL,
    email varchar(255) DEFAULT '' NOT NULL,
    website varchar(2048) DEFAULT '' NOT NULL,
    booking_url varchar(2048) DEFAULT '' NOT NULL,
    booking_text text,
    request_email varchar(255) DEFAULT '' NOT NULL,
    price_from decimal(10,2) DEFAULT '0.00' NOT NULL,
    price_info text,
    persons int(11) DEFAULT '0' NOT NULL,
    bedrooms int(11) DEFAULT '0' NOT NULL,
    beds int(11) DEFAULT '0' NOT NULL,
    bathrooms int(11) DEFAULT '0' NOT NULL,
    size_sqm int(11) DEFAULT '0' NOT NULL,
    units int(11) DEFAULT '0' NOT NULL,
    season_info text,
    capacity_note text,
    features int(11) unsigned DEFAULT '0' NOT NULL,
    certificates int(11) unsigned DEFAULT '0' NOT NULL,
    equipment_text mediumtext,
    opening_times text,
    accessibility_text text,
    sustainability_text text,
    seo_title varchar(255) DEFAULT '' NOT NULL,
    meta_description text,
    og_title varchar(255) DEFAULT '' NOT NULL,
    og_description text,
    noindex smallint(5) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY slug (slug(191)),
    KEY type (type),
    KEY district (district),
    KEY stars (stars),
    KEY visible (hidden,deleted,starttime,endtime)
);

CREATE TABLE tx_gastgeber_domain_model_type (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    description text,
    icon int(11) unsigned DEFAULT '0' NOT NULL,
    icon_class varchar(255) DEFAULT '' NOT NULL,
    show_in_filter smallint(5) unsigned DEFAULT '1' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY slug (slug(191))
);

CREATE TABLE tx_gastgeber_domain_model_featuregroup (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    description text,
    icon int(11) unsigned DEFAULT '0' NOT NULL,
    icon_class varchar(255) DEFAULT '' NOT NULL,
    collapsed smallint(5) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY slug (slug(191))
);

CREATE TABLE tx_gastgeber_domain_model_feature (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    description text,
    `group` int(11) unsigned DEFAULT '0' NOT NULL,
    icon int(11) unsigned DEFAULT '0' NOT NULL,
    icon_class varchar(255) DEFAULT '' NOT NULL,
    filterable smallint(5) unsigned DEFAULT '1' NOT NULL,
    show_in_card smallint(5) unsigned DEFAULT '1' NOT NULL,
    show_in_detail smallint(5) unsigned DEFAULT '1' NOT NULL,
    top_feature smallint(5) unsigned DEFAULT '0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY feature_group (`group`),
    KEY slug (slug(191))
);

CREATE TABLE tx_gastgeber_domain_model_district (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    description text,
    latitude varchar(64) DEFAULT '' NOT NULL,
    longitude varchar(64) DEFAULT '' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY slug (slug(191))
);

CREATE TABLE tx_gastgeber_domain_model_certificate (
    uid int(11) unsigned NOT NULL auto_increment,
    pid int(11) DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    deleted smallint(5) unsigned DEFAULT '0' NOT NULL,
    hidden smallint(5) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sys_language_uid int(11) DEFAULT '0' NOT NULL,
    l10n_parent int(11) unsigned DEFAULT '0' NOT NULL,
    l10n_diffsource mediumblob,
    title varchar(255) DEFAULT '' NOT NULL,
    slug varchar(2048) DEFAULT '' NOT NULL,
    description text,
    issuer varchar(255) DEFAULT '' NOT NULL,
    icon int(11) unsigned DEFAULT '0' NOT NULL,
    icon_class varchar(255) DEFAULT '' NOT NULL,
    url varchar(2048) DEFAULT '' NOT NULL,
    rating_value decimal(4,1) DEFAULT '0.0' NOT NULL,
    PRIMARY KEY (uid),
    KEY parent (pid),
    KEY slug (slug(191))
);

CREATE TABLE tx_gastgeber_host_feature_mm (
    uid_local int(11) unsigned DEFAULT '0' NOT NULL,
    uid_foreign int(11) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sorting_foreign int(11) unsigned DEFAULT '0' NOT NULL,
    KEY uid_local (uid_local),
    KEY uid_foreign (uid_foreign)
);

CREATE TABLE tx_gastgeber_host_certificate_mm (
    uid_local int(11) unsigned DEFAULT '0' NOT NULL,
    uid_foreign int(11) unsigned DEFAULT '0' NOT NULL,
    sorting int(11) unsigned DEFAULT '0' NOT NULL,
    sorting_foreign int(11) unsigned DEFAULT '0' NOT NULL,
    KEY uid_local (uid_local),
    KEY uid_foreign (uid_foreign)
);
