<?php

declare(strict_types=1);

namespace D3Werk\Gastgeber\Controller;

use GeorgRinger\News\Domain\Model\News;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

/**
 * Gastgeber wrapper around EXT:news' NewsController.
 *
 * The list links generated by EXT:news usually use the historical tx_news_pi1
 * namespace. The custom Gastgeber detail content element itself has the
 * namespace tx_gastgeber_detail. This controller bridges both namespaces so the
 * dedicated "Gastgeber: Detailansicht" content element can resolve detail
 * records from tx_news_pi1[news] as well as from tx_gastgeber_detail[news].
 */
class NewsController extends \GeorgRinger\News\Controller\NewsController
{
    public function detailAction(?News $news = null, $currentPage = 1): ResponseInterface
    {
        if ($news === null) {
            $news = $this->resolveNewsFromForeignNamespace();
        }

        return parent::detailAction($news, $currentPage);
    }

    private function resolveNewsFromForeignNamespace(): ?News
    {
        $newsUid = $this->resolveNewsUidFromQueryParams();
        if ($newsUid <= 0) {
            return null;
        }

        if ($this->isPreviewOfHiddenRecordsEnabled()) {
            return $this->newsRepository->findByUid($newsUid, false);
        }

        return $this->newsRepository->findByUid($newsUid);
    }

    private function resolveNewsUidFromQueryParams(): int
    {
        $request = $GLOBALS['TYPO3_REQUEST'] ?? null;
        if (!$request instanceof ServerRequestInterface) {
            return 0;
        }

        $queryParams = $request->getQueryParams();
        $candidateNamespaces = [
            'tx_news_pi1',
            'tx_gastgeber_detail',
            'tx_gastgeber_list',
        ];

        foreach ($candidateNamespaces as $namespace) {
            $namespaceArguments = $queryParams[$namespace] ?? null;
            if (!is_array($namespaceArguments)) {
                continue;
            }

            $newsUid = (int)($namespaceArguments['news'] ?? 0);
            if ($newsUid > 0) {
                return $newsUid;
            }

            $previewUid = (int)($namespaceArguments['news_preview'] ?? 0);
            if ($previewUid > 0) {
                return $previewUid;
            }
        }

        return 0;
    }
}
