services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  D3Werk\Gastgeber\:
    resource: '../Classes/*'

  D3Werk\Gastgeber\Command\SetupDefaultsCommand:
    tags:
      - name: 'console.command'
        command: 'gastgeber:setup:defaults'
        description: 'Legt Standarddaten für das Gastgeberverzeichnis an.'
